"""
skills/browser_awareness/schemas.py

Typed data contracts for the Browser Awareness capability.

The pipeline is deliberately split so Hermes never controls the browser:

    PageSnapshot (what is on the page)     — produced by the inspector
    InspectionResult / RecommendedAction   — produced by Hermes (JSON only)
    ActionOutcome                          — produced by the safe executor

Hermes' output is validated against these models before anything is
executed: it can only reference elements that actually exist on the
page (by snapshot element id) and can only request actions from the
allow-list below.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Page model (inspector output)
# ---------------------------------------------------------------------------

ElementKind = Literal[
    "link", "button", "input", "textarea", "select", "checkbox", "radio", "nav", "other"
]

ACTION_TYPES = ("navigate", "click", "type", "select", "check", "uncheck", "submit", "scroll")

# Element kinds an action type may target. A mismatch is rejected before
# the browser is touched (Hermes cannot click into a text input, etc.).
ACTION_KIND_RULES: dict[str, tuple[str, ...]] = {
    "click": ("link", "button", "checkbox", "radio", "nav", "other"),
    "type": ("input", "textarea"),
    "select": ("select",),
    "check": ("checkbox",),
    "uncheck": ("checkbox",),
    "submit": ("button", "input"),
    "scroll": ("other", "nav", "button", "link"),
    # navigate needs no element.
}


class ElementInfo(BaseModel):
    """One interactive element found on the page."""

    id: str  # stable id assigned by the inspector ("el_1", ...)
    kind: ElementKind
    text: str = ""
    placeholder: str = ""
    label: str = ""  # aria-label / visible label when available
    name: str = ""
    href: str = ""
    selector: str = ""  # CSS selector generated by the inspector
    visible: bool = True
    enabled: bool = True
    confidence: float = 1.0


class PageSnapshot(BaseModel):
    """Compact, sanitized representation of one page (never the full DOM)."""

    url: str = ""
    title: str = ""
    text: str = ""  # capped visible text, for Hermes context
    elements: list[ElementInfo] = Field(default_factory=list)
    text_truncated: bool = False
    elements_truncated: bool = False


# ---------------------------------------------------------------------------
# Hermes observation model (must be produced as strict JSON)
# ---------------------------------------------------------------------------


class RecommendedAction(BaseModel):
    """One action Hermes recommends the Brain may execute."""

    type: Literal["navigate", "click", "type", "select", "check", "uncheck", "submit", "scroll"]
    element_id: str | None = None  # must exist in the current PageSnapshot
    value: str | None = None  # text to type / option to select / scroll direction
    url: str | None = None  # navigate target (http/https only)
    rationale: str = ""
    requires_confirmation: bool = False  # high-impact (purchase/send/delete-like)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)


class InspectionResult(BaseModel):
    """Hermes' observation of the page against the user objective."""

    status: Literal["continue", "done", "blocked"] = "continue"
    understanding: str = ""
    action: RecommendedAction | None = None
    message: str = ""


# ---------------------------------------------------------------------------
# Executor output
# ---------------------------------------------------------------------------


class ActionOutcome(BaseModel):
    ok: bool
    status: Literal["executed", "needs_confirmation", "blocked", "invalid", "error"]
    message: str = ""
    detail: str = ""


class BrowserTaskResult(BaseModel):
    """Final result of one Browser Awareness run."""

    success: bool
    status: Literal["completed", "blocked", "needs_confirmation", "failed", "planned"]
    url: str = ""
    objective: str = ""
    message: str = ""
    steps: list[str] = Field(default_factory=list)
    final_understanding: str = ""


def validate_inspection(inspection: InspectionResult, snapshot: PageSnapshot) -> list[str]:
    """Pure validation of a Hermes recommendation against the page snapshot.

    Returns a list of human-readable problems; an empty list means the
    action may be executed. This is the safety gate between Hermes and
    the browser executor.
    """
    if inspection.status == "done":
        return []
    if inspection.status == "blocked":
        return [inspection.message or "Hermes reports the objective cannot proceed."]
    if inspection.action is None:
        return ["Hermes returned no action."]

    action = inspection.action
    problems: list[str] = []

    if action.type not in ACTION_TYPES:
        problems.append(f"Unknown action type: {action.type}")

    if action.type == "navigate":
        url = (action.url or "").strip()
        if not url.lower().startswith(("http://", "https://")):
            problems.append("navigate requires an http(s) URL.")
        return problems

    element = _find_element(snapshot, action.element_id)
    if element is None:
        problems.append(
            f"Action '{action.type}' references element '{action.element_id}' "
            "which is not on the page."
        )
        return problems

    if not element.visible:
        problems.append(f"Element '{action.element_id}' is hidden.")
    if not element.enabled and action.type in (
        "click",
        "type",
        "select",
        "check",
        "uncheck",
        "submit",
    ):
        problems.append(f"Element '{action.element_id}' is disabled.")

    allowed = ACTION_KIND_RULES.get(action.type, ())
    if allowed and element.kind not in allowed:
        problems.append(
            f"Cannot {action.type} on a {element.kind} element ('{action.element_id}')."
        )

    if action.type in ("type", "select", "check", "uncheck") and not action.value:
        if action.type not in ("check", "uncheck"):
            problems.append(f"{action.type} requires a value.")

    return problems


def _find_element(snapshot: PageSnapshot, element_id: str | None) -> ElementInfo | None:
    if not element_id:
        return None
    for element in snapshot.elements:
        if element.id == element_id:
            return element
    return None
